### ISSUE TITLE
ラズベリーパイで通信を受けとる関数の作成

### ISSUE THREAD

**Issue by nabefuta220** [IBARAKI-I-PBL-6/PBL#8]
- [ ] ラズベリーパイで通信を受けとる関数の作成

_Originally posted by @nabefuta220 in https://github.com/IBARAKI-I-PBL-6/PBL/issues/6#issuecomment-954428361_

**Comment by st18137yy** [comment]
![pbl_raspi_in](https://user-images.githubusercontent.com/70876802/141396520-fc10de4c-c9da-492a-bd23-0f24aa9812a3.jpg)
